
default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: refactoring_rails_blog_development
test:
  <<: *default
  database: refactoring_rails_blog_test

production:
  <<: *default
  database: refactoring_rails_blog_production
